### ISSUE TITLE
Upgrade NodeHoster to .NET 8 and Yarp.ReverseProxy to 2.1.0

### ISSUE THREAD

**Issue by maan002** [hajkmap/NodeHoster#1]
Time to upgrade to .NET 8.0?

.NET 7.0 ends at may 24, 2024. It would be nice to not have to reinstall all servers in a couple of months.

Also, the Yarp.ReverseProxy 2.0.0 has to be upgraded.

**Comment by jesade-vbg** [comment]
Well, since the user base of NodeHoster is still very limited.... I'll say it's a really good idea to upgrade.
